name: Run Tests

on:
  pull_request:
    types:
      - opened

jobs:
  test_and_lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run Tests
      run: npx nx run-many -t test --all

    - name: Run Linting
      run: npx nx run-many -t lint --all
